server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 1. Buat SPA React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy API ke dashboard-service
    location /api/ {
        proxy_pass http://dashboard-service:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Proxy WebSocket ke dashboard-service
    location /ws-dashboard {
        proxy_pass http://dashboard-service:8080/ws-dashboard;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location /api/search {
        proxy_pass http://search-service:8080/api/search;
    }

    location /api/analytics {
        proxy_pass http://analytics-service:8080/api/analytics;
    }
}